# Generated by Django 4.2.5 on 2025-06-20 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_demandorderitem_actual_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='demandorderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='binding',
        ),
        migrations.AlterUniqueTogether(
            name='orderreview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orderreview',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='orderreview',
            name='order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='DemandOrder',
        ),
        migrations.DeleteModel(
            name='DemandOrderItem',
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
        migrations.DeleteModel(
            name='OrderReview',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
