# Generated by Django 4.2.5 on 2025-06-20 02:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_couplebinding_unbound_at_couplebinding_unbound_by_and_more'),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('CONFIRMED', '已确认'), ('ORDERED', '已下单'), ('COMPLETED', '已完成'), ('RATED', '已评价'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='订单状态')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='总价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_orders', to='users.couplebinding', verbose_name='所属情侣绑定')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_demand_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '需求订单',
                'verbose_name_plural': '需求订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='1-5分', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='评价人')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.demandorder', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '订单评价',
                'verbose_name_plural': '订单评价',
            },
        ),
        migrations.CreateModel(
            name='DemandOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, help_text='下单时的商品单价', max_digits=10, verbose_name='单价')),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, help_text='接收方填写的实际单价', max_digits=10, null=True, verbose_name='实际价格')),
                ('receiver_notes', models.TextField(blank=True, null=True, verbose_name='接收方备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.demandorder', verbose_name='所属订单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='menus.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '需求订单项',
                'verbose_name_plural': '需求订单项',
            },
        ),
    ]
