# Generated by Django 4.2.5 on 2025-06-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_populate_groups'),
    ]

    operations = [
    ]
