# Generated by Django 4.2.5 on 2025-06-20 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='couplebinding',
            name='unbound_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='解绑时间'),
        ),
        migrations.AddField(
            model_name='couplebinding',
            name='unbound_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_unbindings', to=settings.AUTH_USER_MODEL, verbose_name='发起解绑的用户'),
        ),
        migrations.AlterField(
            model_name='couplebinding',
            name='status',
            field=models.CharField(choices=[('requesting', '请求中'), ('active', '绑定成功'), ('rejected', '已拒绝'), ('unbound', '已解绑')], default='requesting', max_length=20, verbose_name='绑定状态'),
        ),
    ]
