# Generated by Django 4.2.5 on 2025-06-19 01:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_populate_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandorderitem',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='接收方填写的实际单价', max_digits=10, null=True, verbose_name='实际价格'),
        ),
        migrations.AddField(
            model_name='demandorderitem',
            name='receiver_notes',
            field=models.TextField(blank=True, null=True, verbose_name='接收方备注'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='binding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='users.couplebinding', verbose_name='所属情侣绑定'),
        ),
        migrations.AlterField(
            model_name='demandorder',
            name='status',
            field=models.CharField(choices=[('PENDING', '待处理'), ('CONFIRMED', '已确认'), ('ORDERED', '已下单'), ('COMPLETED', '已完成'), ('RATED', '已评价'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='订单状态'),
        ),
        migrations.CreateModel(
            name='CoupleTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='themes/backgrounds/', verbose_name='背景图片')),
                ('theme_color', models.CharField(default='#FFFFFF', help_text='十六进制颜色代码, e.g., #FFFFFF', max_length=7, verbose_name='主题颜色')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('binding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='users.couplebinding', verbose_name='所属情侣绑定')),
            ],
            options={
                'verbose_name': '情侣主题',
                'verbose_name_plural': '情侣主题',
            },
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='1-5分', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='评价人')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.demandorder', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '订单评价',
                'verbose_name_plural': '订单评价',
                'ordering': ['-created_at'],
                'unique_together': {('order', 'creator')},
            },
        ),
    ]
